# Glassdoor Job Reviews: Exploratory Data Analysis

Link to the Data: https://www.kaggle.com/datasets/davidgauthier/glassdoor-job-reviews

In [1]:
import pandas as pd

In [2]:
reviews_df = pd.read_csv('glassdoor_reviewss.csv')

# 1. Data Cleaning: Determine amount of nulls in the data:

In [3]:
reviews_df.isna().sum()

firm                        0
date_review                 0
job_title                   0
current                     0
location               297343
overall_rating              0
work_life_balance      149894
culture_values         191373
diversity_inclusion    702500
career_opp             147501
comp_benefits          150082
senior_mgmt            155876
recommend                   0
ceo_approv                  0
outlook                     0
headline                 2590
pros                        2
cons                       13
dtype: int64

In [4]:
reviews_df.location.nunique()

14486

In [5]:
reviews_df.columns

Index(['firm', 'date_review', 'job_title', 'current', 'location',
       'overall_rating', 'work_life_balance', 'culture_values',
       'diversity_inclusion', 'career_opp', 'comp_benefits', 'senior_mgmt',
       'recommend', 'ceo_approv', 'outlook', 'headline', 'pros', 'cons'],
      dtype='object')

In [6]:
reviews_df[['firm', 'overall_rating']].groupby(['firm']).mean().sort_values(by = 'overall_rating', ascending = False)

                              overall_rating
firm
The-Survey-Association              5.000000
Time-Etc                            4.785714
Northern-Gas-and-Power              4.719682
CarShop-UK                          4.651163
Michelmores                         4.610390
...                                      ...
Diligenta                           2.363636
Macdonald-Hotels-and-Resorts        2.330472
James-Hay-Partnership               2.311111
Creative-Support                    2.257778
The-Range                           2.200000

[428 rows x 1 columns]

In [7]:
reviews_df.describe(include = 'all')

,firm,date_review,job_title,current,location,overall_rating,work_life_balance,culture_values,diversity_inclusion,career_opp,comp_benefits,senior_mgmt,recommend,ceo_approv,outlook,headline,pros,cons
count,838566,838566,838566,838566,541223,838566.000000,688672.000000,647193.000000,136066.000000,691065.000000,688484.000000,682690.000000,838566,838566,838566,835976,838564,838553
unique,428,4813,62275,29,14486,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,4,4,390454,778559,777133
top,IBM,2021-01-13,Anonymous Employee,Current Employee,"London, England, England",NaN,NaN,NaN,NaN,NaN,NaN,NaN,v,o,v,Good,Great company to work for,None that I can think of
freq,60436,1761,162649,209599,58665,NaN,NaN,NaN,NaN,NaN,NaN,NaN,427865,311433,301413,14300,720,1156
mean,NaN,NaN,NaN,NaN,NaN,3.655956,3.375735,3.590164,3.966612,3.461825,3.398109,3.176576,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,1.174684,1.305874,1.323280,1.190937,1.271295,1.218738,1.330720,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,3.000000,2.000000,3.000000,3.000000,3.000000,3.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,4.000000,4.000000,4.000000,4.000000,4.000000,3.000000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,5.000000,4.000000,5.000000,5.000000,5.000000,4.000000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Find Total Rows and Columns

reviews_df.shape

(838566, 18)

In [9]:
# Check Data Types

reviews_df.info() # Switch date_review to datetime64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 838566 entries, 0 to 838565
Data columns (total 18 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   firm                 838566 non-null  object
 1   date_review          838566 non-null  object
 2   job_title            838566 non-null  object
 3   current              838566 non-null  object
 4   location             541223 non-null  object
 5   overall_rating       838566 non-null  int64
 6   work_life_balance    688672 non-null  float64
 7   culture_values       647193 non-null  float64
 8   diversity_inclusion  136066 non-null  float64
 9   career_opp           691065 non-null  float64
 10  comp_benefits        688484 non-null  float64
 11  senior_mgmt          682690 non-null  float64
 12  recommend            838566 non-null  object
 13  ceo_approv           838566 non-null  object
 14  outlook              838566 non-null  object
 15  headline             835976 non-null  object
 16  pros                 838564 non-null  object
 17  cons                 838553 non-null  object
dtypes: float64(6), int64(1), object(11)
memory usage: 115.2+ MB

In [10]:
# Show Data Types

reviews_df.dtypes.to_frame()

                           0
firm                  object
date_review           object
job_title             object
current               object
location              object
overall_rating         int64
work_life_balance    float64
culture_values       float64
diversity_inclusion  float64
career_opp           float64
comp_benefits        float64
senior_mgmt          float64
recommend             object
ceo_approv            object
outlook               object
headline              object
pros                  object
cons                  object

In [11]:
# Recommend column percentages

reviews_df.recommend.value_counts(normalize = True).mul(100).round(1).astype(str) + '%'

recommend
v    51.0%
o    27.9%
x    21.0%
Name: proportion, dtype: object

In [12]:
# Counts of uniques in the data

reviews_df.nunique()

firm                      428
date_review              4813
job_title               62275
current                    29
location                14486
overall_rating              5
work_life_balance           5
culture_values              5
diversity_inclusion         5
career_opp                  5
comp_benefits               5
senior_mgmt                 5
recommend                   3
ceo_approv                  4
outlook                     4
headline               390454
pros                   778559
cons                   777133
dtype: int64

In [56]:
# Finding reviews for specific firms

bool = reviews_df['firm'] == 'Time-Etc'
reviews_df[bool]

,firm,date_review,job_title,current,location,overall_rating,work_life_balance,culture_values,diversity_inclusion,career_opp,comp_benefits,senior_mgmt,recommend,ceo_approv,outlook,headline,pros,cons
784337,Time-Etc,2016-04-28,Customer Service,"Former Employee, more than 1 year","Birmingham, England, England",1,2.0,2.0,NaN,1.0,1.0,1.0,x,o,v,Could have been great..,Clients are lovely\r\nReally friendly customer...,Low salary for high workload \r\nLittle apprec...
784338,Time-Etc,2016-10-10,Anonymous Employee,Current Employee,NaN,5,5.0,5.0,NaN,5.0,5.0,5.0,v,o,v,Great company to work for.,Able to share ideas and implement change.\r\nG...,None that I can think of.
784339,Time-Etc,2016-10-10,Virtual Assistant,Current Employee,"Wichita, KS",5,5.0,5.0,NaN,5.0,5.0,5.0,v,o,v,Love this company!!,I have been working for Time Etc. as a Virtual...,I have not encountered any Cons in the time I ...
784340,Time-Etc,2016-10-14,,Current Employee,"Birmingham, England, England",5,5.0,5.0,NaN,3.0,5.0,5.0,v,o,o,Working in Timeetc Birmingham Office,"Really great team of people, and easy to settl...",Often very busy so not for anyone who is not p...
784341,Time-Etc,2017-01-04,Virtual Assistant,"Current Employee, less than 1 year","Birmingham, England, England",5,5.0,5.0,NaN,3.0,1.0,4.0,v,o,v,Virtual assistance,Work flexible hours to fit around my life style,not regular amount of income
784342,Time-Etc,2017-01-09,Anonymous Employee,Current Employee,NaN,5,5.0,5.0,NaN,5.0,5.0,5.0,v,o,v,Exciting and Inspiring company to work for,Fair and generous pay\r\nDedication and hard w...,No cons to speak of. A genuinely great place t...
784343,Time-Etc,2017-02-08,Account Manager,"Current Employee, less than 1 year","Birmingham, England, England",5,5.0,5.0,NaN,5.0,5.0,5.0,v,v,v,Great place to work :),There are a lot of pros! \r\n* Variety every d...,"Nothing really, I enjoy it a lot.\r\nThere are..."
784344,Time-Etc,2017-02-16,Virtual Assistant,"Current Employee, less than 1 year","Free Home, GA",4,4.0,4.0,NaN,4.0,4.0,4.0,v,v,r,Interesting company,"Your choice of clients, support and help are a...","They pay you thru PayPal, that's the only opti..."
784345,Time-Etc,2017-03-13,Account Manager,"Current Employee, less than 1 year","Birmingham, England, England",5,4.0,5.0,NaN,5.0,4.0,5.0,v,v,v,This is a great place to work!,A fantastic team of people to work with\r\nStr...,"There is a lot to balance sometimes, and that'..."
784346,Time-Etc,2017-03-13,Anonymous Employee,"Current Employee, less than 1 year","Birmingham, England, England",5,NaN,5.0,NaN,5.0,5.0,5.0,v,v,o,Great company to work for!,- Lovely team who are really supportive and mo...,Nothing! \r\n- There is always someone there i...
784347,Time-Etc,2017-07-31,Anonymous Employee,"Current Employee, less than 1 year","Birmingham, England, England",5,5.0,5.0,NaN,5.0,5.0,5.0,v,v,v,Support Specialist,"-Superb team of people to work with, real fami...","Can get busy at times, but I view this as a go..."
784348,Time-Etc,2017-08-01,Resourcing Specialist,"Current Employee, less than 1 year","Birmingham, England, England",5,4.0,5.0,NaN,5.0,5.0,5.0,v,v,v,I LOVE coming to work!,"- awesome team to work with, everyone is passi...",I struggle to think of anything I don't enjoy ...
784349,Time-Etc,2017-09-13,Client Happiness Assistant,"Current Employee, less than 1 year","Birmingham, England, England",5,5.0,5.0,NaN,5.0,5.0,5.0,v,v,v,Client Happiness Assistant,The Time Etc team are some of the most kindest...,"Honestly, could not name one"
784350,Time-Etc,2017-09-15,Client Happiness,"Current Employee, less than 1 year","Birmingham, England, England",5,5.0,5.0,NaN,5.0,5.0,5.0,v,v,v,Dream Job,Time etc is one of the few companies what genu...,It can be very busy! I personally get emotiona...
784351,Time-Etc,2017-09-15,Client Happiness Assistant,"Current Employee, less than 1 year","Birmingham, England, England",5,5.0,5.0,NaN,5.0,5.0,5.0,v,v,v,Great atmosphere and supportive team!,- Incredibly supportive team and management\r\...,There is lots of work to do so I wouldn't reco...
784352,Time-Etc,2017-12-14,Call Answering Team,"Current Employee, more than 3 years","Birmingham, England, England",5,5.0,5.0,NaN,5.0,5.0,5.0,v,v,v,A fantastic place to work,-Lovely colleagues and team members\r\n-Nice c...,I struggle to think of any Cons.\r\n\r\nThe jo...
784353,Time-Etc,2017-12-20,Call Answering Team,"Current Employee, more than 3 years","Birmingham, England, England",5,5.0,5.0,NaN,5.0,5.0,5.0,v,v,v,Great atmosphere and even better team,Exciting work environment.\r\nFantastic team -...,I have no cons - I've been working here over 3...
784354,Time-Etc,2017-12-22,Client Happiness Team,"Current Employee, less than 1 year","Birmingham, England, England",5,5.0,5.0,NaN,5.0,4.0,5.0,v,v,v,A company that actually cares,Time etc actually care about you and want you ...,No cons I can think of
784355,Time-Etc,2018-01-29,Client Happiness,Current Employee,NaN,5,5.0,5.0,NaN,5.0,5.0,5.0,v,v,v,Great place to work!,"- Lovely place to work, with great people\r\n-...",No cons to think of!
784356,Time-Etc,2018-05-01,Client Onboarding,"Current Employee, less than 1 year","Birmingham, England, England",5,5.0,5.0,NaN,5.0,5.0,5.0,v,v,v,Working at Time etc!,- Management very supportive \r\n- Encourageme...,- Actually can't think of anything!
784357,Time-Etc,2019-03-12,Client Happiness Assistant,"Current Employee, less than 1 year","Birmingham, England, England",5,5.0,5.0,NaN,5.0,5.0,5.0,v,v,v,Client Happiness Assistant,- Great team members who are all very supporti...,None to share at this time
784358,Time-Etc,2019-03-20,Anonymous Employee,Current Employee,NaN,5,5.0,5.0,NaN,5.0,5.0,5.0,v,v,r,"Easily, the happiest I have felt in a job role.",The team are amazing. You are guaranteed to la...,This box has been blank for a while - so I hav...
784359,Time-Etc,2019-03-21,Client Happiness,"Current Employee, less than 1 year","Birmingham, England, England",5,4.0,5.0,NaN,5.0,5.0,5.0,v,v,v,Employee Happiness&Appreciation,"Surrounded by amazing, motivating and encourag...","Zero, None, Zilch, Nil, Nope"
784360,Time-Etc,2019-04-01,Anonymous Employee,"Current Employee, more than 1 year",NaN,5,5.0,5.0,NaN,5.0,5.0,5.0,v,o,v,It just fits,I have loved working with Time Etc. The compa...,I wouldn't say this is a con towards the compa...
784361,Time-Etc,2019-04-29,Executive Assistant,"Current Employee, less than 1 year",NaN,4,5.0,NaN,NaN,4.0,4.0,NaN,v,o,v,Good experience,"Flexible, work from home, my own terms",Pay close attention to your money. What's calc...
784362,Time-Etc,2019-06-11,Virtual Assistant,"Current Employee, less than 1 year","Orlando, FL",5,4.0,4.0,NaN,5.0,4.0,5.0,v,v,o,Great Company,Great customer support. Very organized. Inter...,Can't think of any cons.
784363,Time-Etc,2019-07-17,Virtual Assistant,"Current Employee, less than 1 year","London, England, England",5,4.0,5.0,NaN,4.0,NaN,5.0,v,o,o,Working as a VA with TIME ETC,Account Managers are very good at communicatin...,Would benefit having a mobile app.
784364,Time-Etc,2019-11-15,Client Relationship Manager,"Current Employee, less than 1 year","Birmingham, England, England",5,5.0,5.0,NaN,5.0,5.0,5.0,v,v,o,Lovely place to work,"A really relaxed office, full of positive peop...",Nothing I can think of at the moment.
784365,Time-Etc,2020-01-16,Virtual Assistant,"Current Employee, less than 1 year",NaN,5,5.0,5.0,NaN,5.0,4.0,5.0,v,v,v,Great platform for VA's,Everything is well organized and constant clie...,Pay only once a month
784366,Time-Etc,2020-01-19,VA Assistant,Current Employee,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,o,o,o,Na,Its kinda enjoyable but the pay isn’t enough,Stop giving u work after 2 weeks
784367,Time-Etc,2020-03-08,Executive Assistant,"Current Employee, more than 5 years","London, England, England",5,5.0,5.0,NaN,5.0,4.0,5.0,v,v,v,Flexible,Choose your hours and holidays.,"None, but you do have to be great at what you do!"
784368,Time-Etc,2020-07-03,Virtual Assistant,"Current Employee, less than 1 year","Edinburgh, Scotland, Scotland",5,5.0,5.0,NaN,5.0,NaN,NaN,v,v,v,Enjoy working for Time etc.,"Time etc. is efficient, gives you great opport...",There is no cons working for Time etc.
784369,Time-Etc,2020-11-16,Freelance Virtual Assistant,Current Employee,"Tulsa, OK",5,5.0,3.0,5.0,5.0,3.0,5.0,v,r,v,Working with Time,Are you struggling to complete mundane everyda...,It can be hard to find help for more complex t...
784370,Time-Etc,2020-11-20,Freelance Virtual Assistant,Current Employee,"Omaha, NE",3,3.0,4.0,4.0,3.0,4.0,4.0,x,r,r,Good people but not enough work available,Time etc is very informative and supportive,There aren't enough tasks available.
784371,Time-Etc,2021-01-05,Anonymous Employee,"Current Employee, less than 1 year","Charlotte, NC",5,5.0,5.0,5.0,5.0,5.0,5.0,v,o,v,I literally just hot hired and I’m so excited ...,The flexibility of having a healthy work-life ...,I have not encountered any cons yet as I liter...
784372,Time-Etc,2021-02-01,Client Happiness,"Current Employee, more than 3 years","Birmingham, England, England",5,5.0,5.0,5.0,5.0,5.0,5.0,v,v,v,Best place I've worked,"I really enjoy working at Time etc, I've liter...",There are literally no cons.
784373,Time-Etc,2021-02-15,Research Assistant,"Former Employee, more than 3 years",NaN,4,5.0,5.0,NaN,5.0,2.0,NaN,v,o,o,Enjoyed working here,"Flexible, work from home, interesting",Hourly rate could be higher
784374,Time-Etc,2021-03-04,Freelance Virtual Assistant,"Current Employee, less than 1 year","Chicago, IL",5,5.0,4.0,4.0,5.0,4.0,4.0,v,v,v,Flexibility,"Flexibility, lots of assistance when getting s...",I recently started so do not have any cons as ...
784375,Time-Etc,2021-05-11,Virtual Assistant,Current Employee,"Tyler, TX",5,5.0,5.0,5.0,4.0,4.0,5.0,v,o,v,Great Company to work for,Pick your own hours\r\nChoose which opportunit...,Paid once a month\r\nSometimes don't get the b...
784376,Time-Etc,2021-05-17,Client Happiness,"Current Employee, more than 1 year","Birmingham, England, England",5,4.0,5.0,5.0,5.0,5.0,5.0,v,v,v,Great place to work.,The company is one of the best I have ever wor...,No cons with working here.
784377,Time-Etc,2021-05-17,Office & Happiness Manager,Current Employee,"Birmingham, England, England",5,5.0,5.0,5.0,5.0,5.0,5.0,v,v,v,Feeling valued,"You don't just feel like a number here, you ar...",I can't think of any!
784378,Time-Etc,2021-05-26,Assistant Manager,Current Employee,"Katy, TX",5,5.0,5.0,5.0,5.0,5.0,5.0,v,v,v,Good,Good team and boss\r\nGreat work\r\nGreat Salary,Your work Saturday \r\nBusy\r\nA lot of work